// UI 제작용 테스트 목데이터
// API 연동 시, 삭제 예정

const MINUTE_MS = 60 * 1000;
const HOUR_MS = 60 * MINUTE_MS;
const DAY_MS = 24 * HOUR_MS;
const KST_OFFSET_MS = 9 * HOUR_MS;

function createdAtAgo(milliseconds) {
  const kstDate = new Date(Date.now() - milliseconds + KST_OFFSET_MS);
  const dateString = kstDate.toISOString().slice(0, 19);

  return `${dateString}+09:00`;
}

export const MOCK_NOTIFICATION_RESPONSE = {
  items: [
    {
      id: "100",
      type: "CARD_SOLD",
      userNickname: "카드수집가",
      cardGrade: "COMMON",
      cardName: "시나모롤",
      quantity: 1,
      relatedSaleListingId: "30",
      relatedExchangeId: null,
      relatedPurchaseId: "40",
      isRead: false,
      createdAt: createdAtAgo(30 * 1000),
    },
    {
      id: "99",
      type: "EXCHANGE_OFFER_RECEIVED",
      userNickname: "피카츄러버",
      cardGrade: "COMMON",
      cardName: "이브이 - 정글 #51",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "50",
      relatedPurchaseId: null,
      isRead: false,
      createdAt: createdAtAgo(5 * MINUTE_MS),
    },
    {
      id: "98",
      type: "EXCHANGE_ACCEPTED",
      userNickname: "버섯왕국주민",
      cardGrade: "COMMON",
      cardName: "피치공주 (#003)",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "51",
      relatedPurchaseId: null,
      isRead: false,
      createdAt: createdAtAgo(59 * MINUTE_MS),
    },
    {
      id: "97",
      type: "EXCHANGE_REJECTED",
      userNickname: "리본컬렉터",
      cardGrade: "RARE",
      cardName: "마이멜로디",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "52",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(HOUR_MS),
    },
    {
      id: "96",
      type: "CARD_SOLD_OUT",
      userNickname: null,
      cardGrade: "LEGENDARY",
      cardName: "BT26-075 스커지카이롭몬",
      quantity: 0,
      relatedSaleListingId: "31",
      relatedExchangeId: null,
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(23 * HOUR_MS),
    },
    {
      id: "95",
      type: "CARD_SOLD",
      userNickname: "디지털테이머",
      cardGrade: "SUPER_RARE",
      cardName: "아이기오투스몬: 다크",
      quantity: 3,
      relatedSaleListingId: "32",
      relatedExchangeId: null,
      relatedPurchaseId: "41",
      isRead: true,
      createdAt: createdAtAgo(12 * HOUR_MS),
    },
    {
      id: "94",
      type: "EXCHANGE_OFFER_RECEIVED",
      userNickname: "별빛트레이더",
      cardGrade: "LEGENDARY",
      cardName: "헬로키티",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "53",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(DAY_MS),
    },
    {
      id: "93",
      type: "EXCHANGE_ACCEPTED",
      userNickname: "레어헌터",
      cardGrade: "RARE",
      cardName: "동키콩, 골프 (#185)",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "54",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(2 * DAY_MS),
    },
    {
      id: "92",
      type: "CARD_SOLD",
      userNickname: "포토카드장인",
      cardGrade: "SUPER_RARE",
      cardName: "망나뇽 - 화석 #19",
      quantity: 2,
      relatedSaleListingId: "33",
      relatedExchangeId: null,
      relatedPurchaseId: "42",
      isRead: true,
      createdAt: createdAtAgo(4 * DAY_MS),
    },
    {
      id: "91",
      type: "CARD_SOLD_OUT",
      userNickname: null,
      cardGrade: "RARE",
      cardName: "폼폼푸린",
      quantity: 0,
      relatedSaleListingId: "34",
      relatedExchangeId: null,
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(6 * DAY_MS),
    },
    {
      id: "90",
      type: "EXCHANGE_REJECTED",
      userNickname: "구름위시나몬",
      cardGrade: "LEGENDARY",
      cardName: "요시 (#149)",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "55",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(7 * DAY_MS),
    },
    {
      id: "89",
      type: "CARD_SOLD",
      userNickname: "마리오점퍼",
      cardGrade: "LEGENDARY",
      cardName: "이상해꽃 - 기본 세트 #15",
      quantity: 1,
      relatedSaleListingId: "35",
      relatedExchangeId: null,
      relatedPurchaseId: "43",
      isRead: true,
      createdAt: createdAtAgo(14 * DAY_MS),
    },
    {
      id: "88",
      type: "EXCHANGE_OFFER_RECEIVED",
      userNickname: "전설의교환가",
      cardGrade: "LEGENDARY",
      cardName: "EX12-018 시리우스몬",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "56",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(21 * DAY_MS),
    },
    {
      id: "87",
      type: "CARD_SOLD_OUT",
      userNickname: null,
      cardGrade: "SUPER_RARE",
      cardName: "쿠로미",
      quantity: 0,
      relatedSaleListingId: "36",
      relatedExchangeId: null,
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(28 * DAY_MS),
    },
    {
      id: "86",
      type: "EXCHANGE_ACCEPTED",
      userNickname: "키티프렌즈",
      cardGrade: "RARE",
      cardName: "쿠파, 야구 (#196)",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "57",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(60 * DAY_MS),
    },
    {
      id: "85",
      type: "CARD_SOLD",
      userNickname: "몬스터도감",
      cardGrade: "RARE",
      cardName: "켄타로스 - 정글 #47",
      quantity: 4,
      relatedSaleListingId: "37",
      relatedExchangeId: null,
      relatedPurchaseId: "44",
      isRead: true,
      createdAt: createdAtAgo(120 * DAY_MS),
    },
    {
      id: "84",
      type: "EXCHANGE_REJECTED",
      userNickname: "카드보관소",
      cardGrade: "LEGENDARY",
      cardName: "단테몬",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "58",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(180 * DAY_MS),
    },
    {
      id: "83",
      type: "CARD_SOLD_OUT",
      userNickname: null,
      cardGrade: "COMMON",
      cardName: "구데타마",
      quantity: 0,
      relatedSaleListingId: "38",
      relatedExchangeId: null,
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(330 * DAY_MS),
    },
    {
      id: "82",
      type: "EXCHANGE_OFFER_RECEIVED",
      userNickname: "슈퍼레어픽",
      cardGrade: "SUPER_RARE",
      cardName: "투구푸스 - 화석 #24",
      quantity: 1,
      relatedSaleListingId: null,
      relatedExchangeId: "59",
      relatedPurchaseId: null,
      isRead: true,
      createdAt: createdAtAgo(365 * DAY_MS),
    },
    {
      id: "81",
      type: "CARD_SOLD",
      userNickname: "앨범완성가",
      cardGrade: "LEGENDARY",
      cardName: "시로키 아스나",
      quantity: 1,
      relatedSaleListingId: "39",
      relatedExchangeId: null,
      relatedPurchaseId: "45",
      isRead: true,
      createdAt: createdAtAgo(730 * DAY_MS),
    },
  ],
  nextCursor: "81",
  hasNext: true,
};
