// 테스트 목데이터입니다, api연동시 삭제 예정


export const MOCK_SALE_LIST_RESPONSE = {
  items: [
    {
      id: "100",
      price: 100,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-20T13:00:00.000Z",
      seller: {
        id: "14",
        nickname: "카드보관소",
      },
      photoCard: {
        id: "100",
        name: "BT25-092 시로키 아스나",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-092.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "99",
      price: 260,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-20T12:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "99",
        name: "BT25-097 가디언 팰리스",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-097.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "98",
      price: 260,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-20T11:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "98",
        name: "BT25-057 모나크리자몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-057.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "97",
      price: 290,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-20T10:00:00.000Z",
      seller: {
        id: "12",
        nickname: "키티프렌즈",
      },
      photoCard: {
        id: "97",
        name: "BT25-102 팩토리얼 에어리어",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-102.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "96",
      price: 250,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-20T09:00:00.000Z",
      seller: {
        id: "10",
        nickname: "마리오점퍼",
      },
      photoCard: {
        id: "96",
        name: "BT25-060 리부트몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-060.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "95",
      price: 230,
      initialQuantity: 3,
      remainingQuantity: 3,
      status: "ON_SALE",
      createdAt: "2026-08-19T13:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "95",
        name: "BT25-090 차내일",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-090.png?260529",
        grade: "SUPER_RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "94",
      price: 190,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-19T12:00:00.000Z",
      seller: {
        id: "18",
        nickname: "민트컬렉션",
      },
      photoCard: {
        id: "94",
        name: "BT25-032 레오르몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-032.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "93",
      price: 110,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-19T11:00:00.000Z",
      seller: {
        id: "8",
        nickname: "포토카드장인",
      },
      photoCard: {
        id: "93",
        name: "BT25-033 아이기오몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-033.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "92",
      price: 290,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-19T10:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "92",
        name: "BT25-013 파이라몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT25-013.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "91",
      price: 100,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-19T09:00:00.000Z",
      seller: {
        id: "4",
        nickname: "리본컬렉터",
      },
      photoCard: {
        id: "91",
        name: "EX12-008 토이아구몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-008.png?260529",
        grade: "SUPER_RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "90",
      price: 230,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-18T13:00:00.000Z",
      seller: {
        id: "20",
        nickname: "앨범완성가",
      },
      photoCard: {
        id: "90",
        name: "EX12-039 타키몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-039.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "89",
      price: 280,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-18T12:00:00.000Z",
      seller: {
        id: "20",
        nickname: "앨범완성가",
      },
      photoCard: {
        id: "89",
        name: "EX12-004 오니비몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-004.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "88",
      price: 170,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-18T11:00:00.000Z",
      seller: {
        id: "17",
        nickname: "교환신청중",
      },
      photoCard: {
        id: "88",
        name: "EX12-020 가사몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-020.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "87",
      price: 250,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-18T10:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "87",
        name: "EX12-069 바이러스 버스터즈",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-069.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "86",
      price: 210,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-18T09:00:00.000Z",
      seller: {
        id: "4",
        nickname: "리본컬렉터",
      },
      photoCard: {
        id: "86",
        name: "EX12-047 아마테라스몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-047.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "85",
      price: 170,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-17T13:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "85",
        name: "EX12-074 겐시 대륙 & 아시노 섬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-074.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "84",
      price: 100,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-17T12:00:00.000Z",
      seller: {
        id: "6",
        nickname: "별빛트레이더",
      },
      photoCard: {
        id: "84",
        name: "EX12-018 시리우스몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/EX12-018.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "83",
      price: 250,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-17T11:00:00.000Z",
      seller: {
        id: "8",
        nickname: "포토카드장인",
      },
      photoCard: {
        id: "83",
        name: "BT26-086 단테몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-086.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "82",
      price: 140,
      initialQuantity: 3,
      remainingQuantity: 3,
      status: "ON_SALE",
      createdAt: "2026-08-17T10:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "82",
        name: "BT26-001 어니몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-001.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "81",
      price: 220,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-17T09:00:00.000Z",
      seller: {
        id: "18",
        nickname: "민트컬렉션",
      },
      photoCard: {
        id: "81",
        name: "BT26-051 트래쉬몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-051.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "80",
      price: 250,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-16T13:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "80",
        name: "BT26-037 웨더드라몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-037.png?260529",
        grade: "RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "79",
      price: 120,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-16T12:00:00.000Z",
      seller: {
        id: "5",
        nickname: "디지털테이머",
      },
      photoCard: {
        id: "79",
        name: "BT26-073 아이기오투스몬: 다크",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-073.png?260529",
        grade: "SUPER_RARE",
        category: "DIGIMON",
      },
    },
    {
      id: "78",
      price: 290,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-16T11:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "78",
        name: "BT26-075 스커지카이롭몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-075.png?260529",
        grade: "LEGENDARY",
        category: "DIGIMON",
      },
    },
    {
      id: "77",
      price: 150,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-16T10:00:00.000Z",
      seller: {
        id: "4",
        nickname: "리본컬렉터",
      },
      photoCard: {
        id: "77",
        name: "BT26-010 롤플레잉몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-010.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "76",
      price: 200,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-16T09:00:00.000Z",
      seller: {
        id: "16",
        nickname: "코인마스터",
      },
      photoCard: {
        id: "76",
        name: "BT26-025 레오르몬",
        imageUrl: "https://world.digimoncard.com/images/cardlist/card/BT26-025.png?260529",
        grade: "COMMON",
        category: "DIGIMON",
      },
    },
    {
      id: "75",
      price: 280,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-15T13:00:00.000Z",
      seller: {
        id: "16",
        nickname: "코인마스터",
      },
      photoCard: {
        id: "75",
        name: "모다피 - 정글 #49",
        imageUrl: "https://assets.tcgdex.net/en/base/base2/49/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "74",
      price: 120,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-15T12:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "74",
        name: "딱구리 - 화석 #36",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/36/high.webp",
        grade: "RARE",
        category: "POKEMON",
      },
    },
    {
      id: "73",
      price: 130,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-15T11:00:00.000Z",
      seller: {
        id: "5",
        nickname: "디지털테이머",
      },
      photoCard: {
        id: "73",
        name: "깨비드릴조 - 정글 #36",
        imageUrl: "https://assets.tcgdex.net/en/base/base2/36/high.webp",
        grade: "RARE",
        category: "POKEMON",
      },
    },
    {
      id: "72",
      price: 250,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-15T10:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "72",
        name: "붐볼 - 기본 세트 #21",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/21/high.webp",
        grade: "SUPER_RARE",
        category: "POKEMON",
      },
    },
    {
      id: "71",
      price: 150,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-15T09:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "71",
        name: "캐터피 - 기본 세트 #45",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/45/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "70",
      price: 200,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-14T13:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "70",
        name: "덩쿠리 - 기본 세트 #66",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/66/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "69",
      price: 90,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-14T12:00:00.000Z",
      seller: {
        id: "11",
        nickname: "전설의교환가",
      },
      photoCard: {
        id: "69",
        name: "미니스커트 - 기본 세트 #75",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/75/high.webp",
        grade: "SUPER_RARE",
        category: "POKEMON",
      },
    },
    {
      id: "68",
      price: 130,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-14T11:00:00.000Z",
      seller: {
        id: "4",
        nickname: "리본컬렉터",
      },
      photoCard: {
        id: "68",
        name: "나인테일 - 기본 세트 #12",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/12/high.webp",
        grade: "LEGENDARY",
        category: "POKEMON",
      },
    },
    {
      id: "67",
      price: 200,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-14T10:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "67",
        name: "괴력몬 - 기본 세트 #8",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/8/high.webp",
        grade: "LEGENDARY",
        category: "POKEMON",
      },
    },
    {
      id: "66",
      price: 130,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-14T09:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "66",
        name: "포켓몬 교체 - 기본 세트 #95",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/95/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "65",
      price: 150,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-13T13:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "65",
        name: "투구푸스 - 화석 #9",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/9/high.webp",
        grade: "LEGENDARY",
        category: "POKEMON",
      },
    },
    {
      id: "64",
      price: 130,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-13T12:00:00.000Z",
      seller: {
        id: "1",
        nickname: "카드수집가",
      },
      photoCard: {
        id: "64",
        name: "망나뇽 - 화석 #19",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/19/high.webp",
        grade: "SUPER_RARE",
        category: "POKEMON",
      },
    },
    {
      id: "63",
      price: 290,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-13T11:00:00.000Z",
      seller: {
        id: "6",
        nickname: "별빛트레이더",
      },
      photoCard: {
        id: "63",
        name: "니드리노 - 기본 세트 #37",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/37/high.webp",
        grade: "RARE",
        category: "POKEMON",
      },
    },
    {
      id: "62",
      price: 250,
      initialQuantity: 3,
      remainingQuantity: 3,
      status: "ON_SALE",
      createdAt: "2026-08-13T10:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "62",
        name: "팬텀 - 화석 #5",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/5/high.webp",
        grade: "LEGENDARY",
        category: "POKEMON",
      },
    },
    {
      id: "61",
      price: 280,
      initialQuantity: 3,
      remainingQuantity: 3,
      status: "ON_SALE",
      createdAt: "2026-08-13T09:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "61",
        name: "라프라스 - 화석 #10",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/10/high.webp",
        grade: "LEGENDARY",
        category: "POKEMON",
      },
    },
    {
      id: "60",
      price: 170,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-12T13:00:00.000Z",
      seller: {
        id: "8",
        nickname: "포토카드장인",
      },
      photoCard: {
        id: "60",
        name: "이상해꽃 - 기본 세트 #15",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/15/high.webp",
        grade: "LEGENDARY",
        category: "POKEMON",
      },
    },
    {
      id: "59",
      price: 110,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-12T12:00:00.000Z",
      seller: {
        id: "20",
        nickname: "앨범완성가",
      },
      photoCard: {
        id: "59",
        name: "켄타로스 - 정글 #47",
        imageUrl: "https://assets.tcgdex.net/en/base/base2/47/high.webp",
        grade: "RARE",
        category: "POKEMON",
      },
    },
    {
      id: "58",
      price: 280,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-12T11:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "58",
        name: "투구푸스 - 화석 #24",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/24/high.webp",
        grade: "SUPER_RARE",
        category: "POKEMON",
      },
    },
    {
      id: "57",
      price: 120,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-12T10:00:00.000Z",
      seller: {
        id: "8",
        nickname: "포토카드장인",
      },
      photoCard: {
        id: "57",
        name: "뚜벅쵸 - 정글 #58",
        imageUrl: "https://assets.tcgdex.net/en/base/base2/58/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "56",
      price: 230,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-12T09:00:00.000Z",
      seller: {
        id: "16",
        nickname: "코인마스터",
      },
      photoCard: {
        id: "56",
        name: "콘팡 - 정글 #63",
        imageUrl: "https://assets.tcgdex.net/en/base/base2/63/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "55",
      price: 100,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-11T13:00:00.000Z",
      seller: {
        id: "17",
        nickname: "교환신청중",
      },
      photoCard: {
        id: "55",
        name: "루주라 - 기본 세트 #31",
        imageUrl: "https://assets.tcgdex.net/en/base/base1/31/high.webp",
        grade: "RARE",
        category: "POKEMON",
      },
    },
    {
      id: "54",
      price: 70,
      initialQuantity: 3,
      remainingQuantity: 3,
      status: "ON_SALE",
      createdAt: "2026-08-11T12:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "54",
        name: "리사이클 - 화석 #61",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/61/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "53",
      price: 180,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-11T11:00:00.000Z",
      seller: {
        id: "8",
        nickname: "포토카드장인",
      },
      photoCard: {
        id: "53",
        name: "꼬마돌 - 화석 #47",
        imageUrl: "https://assets.tcgdex.net/en/base/base3/47/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "52",
      price: 180,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-11T10:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "52",
        name: "이브이 - 정글 #51",
        imageUrl: "https://assets.tcgdex.net/en/base/base2/51/high.webp",
        grade: "COMMON",
        category: "POKEMON",
      },
    },
    {
      id: "51",
      price: 70,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-11T09:00:00.000Z",
      seller: {
        id: "10",
        nickname: "마리오점퍼",
      },
      photoCard: {
        id: "51",
        name: "잉어킹 - M-P 프로모 #040/M-P",
        imageUrl: "https://skt-pokemon.co.kr/customer/images/pokemon/card_magikarp.png",
        grade: "RARE",
        category: "POKEMON",
      },
    },
    {
      id: "50",
      price: 150,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-10T13:00:00.000Z",
      seller: {
        id: "17",
        nickname: "교환신청중",
      },
      photoCard: {
        id: "50",
        name: "퍼즐 그룹, 아홉 번째 카드 (#252)",
        imageUrl: "https://mario.wiki.gallery/images/2/2e/Panini_SMTCC_252.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "49",
      price: 170,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-10T12:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "49",
        name: "퍼즐 그룹, 여덟 번째 카드 (#251)",
        imageUrl: "https://mario.wiki.gallery/images/0/0a/Panini_SMTCC_251.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "48",
      price: 130,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-10T11:00:00.000Z",
      seller: {
        id: "5",
        nickname: "디지털테이머",
      },
      photoCard: {
        id: "48",
        name: "퍼즐 그룹, 다섯 번째 카드 (#248)",
        imageUrl: "https://mario.wiki.gallery/images/0/03/Panini_SMTCC_248.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "47",
      price: 230,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-10T10:00:00.000Z",
      seller: {
        id: "18",
        nickname: "민트컬렉션",
      },
      photoCard: {
        id: "47",
        name: "퍼즐 그룹, 첫 번째 카드 (#244)",
        imageUrl: "https://mario.wiki.gallery/images/4/41/Panini_SMTCC_244.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "46",
      price: 270,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-10T09:00:00.000Z",
      seller: {
        id: "6",
        nickname: "별빛트레이더",
      },
      photoCard: {
        id: "46",
        name: "마리오, 피치공주, 키노피오, 쿠파 (#237)",
        imageUrl: "https://mario.wiki.gallery/images/3/3c/Panini_SMTCC_237.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "45",
      price: 220,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-09T13:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "45",
        name: "와루이지 (#228)",
        imageUrl: "https://mario.wiki.gallery/images/2/2e/Panini_SMTCC_228.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "44",
      price: 190,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-09T12:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "44",
        name: "마리오 (#217)",
        imageUrl: "https://mario.wiki.gallery/images/f/fc/Panini_SMTCC_217.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "43",
      price: 270,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-09T11:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "43",
        name: "키노피코, 테니스 (#207)",
        imageUrl: "https://mario.wiki.gallery/images/c/ca/Panini_SMTCC_207.jpg",
        grade: "RARE",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "42",
      price: 230,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-09T10:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "42",
        name: "쿠파, 야구 (#196)",
        imageUrl: "https://mario.wiki.gallery/images/2/2e/Panini_SMTCC_196.jpg",
        grade: "RARE",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "41",
      price: 110,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-09T09:00:00.000Z",
      seller: {
        id: "12",
        nickname: "키티프렌즈",
      },
      photoCard: {
        id: "41",
        name: "동키콩, 골프 (#185)",
        imageUrl: "https://mario.wiki.gallery/images/4/44/Panini_SMTCC_185.jpg",
        grade: "RARE",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "40",
      price: 180,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-08T13:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "40",
        name: "쿠파주니어 (#174)",
        imageUrl: "https://mario.wiki.gallery/images/5/57/Panini_SMTCC_174.jpg",
        grade: "SUPER_RARE",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "39",
      price: 90,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-08T12:00:00.000Z",
      seller: {
        id: "20",
        nickname: "앨범완성가",
      },
      photoCard: {
        id: "39",
        name: "부끄부끄 (#161)",
        imageUrl: "https://mario.wiki.gallery/images/4/4b/Panini_SMTCC_161.jpg",
        grade: "LEGENDARY",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "38",
      price: 70,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-08T11:00:00.000Z",
      seller: {
        id: "1",
        nickname: "카드수집가",
      },
      photoCard: {
        id: "38",
        name: "요시 (#149)",
        imageUrl: "https://mario.wiki.gallery/images/5/56/Panini_SMTCC_149.jpg",
        grade: "LEGENDARY",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "37",
      price: 220,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-08T10:00:00.000Z",
      seller: {
        id: "6",
        nickname: "별빛트레이더",
      },
      photoCard: {
        id: "37",
        name: "?블록 (#138)",
        imageUrl: "https://mario.wiki.gallery/images/3/39/Panini_SMTCC_138.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "36",
      price: 180,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-08T09:00:00.000Z",
      seller: {
        id: "19",
        nickname: "오늘의뽑기",
      },
      photoCard: {
        id: "36",
        name: "징오징오패밀리 (#126)",
        imageUrl: "https://mario.wiki.gallery/images/a/ad/Panini_SMTCC_126.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "35",
      price: 120,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-07T13:00:00.000Z",
      seller: {
        id: "11",
        nickname: "전설의교환가",
      },
      photoCard: {
        id: "35",
        name: "동키콩 & 디디콩 (#113)",
        imageUrl: "https://mario.wiki.gallery/images/c/c3/Panini_SMTCC_113.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "34",
      price: 260,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-07T12:00:00.000Z",
      seller: {
        id: "1",
        nickname: "카드수집가",
      },
      photoCard: {
        id: "34",
        name: "메카쿠파 (#101)",
        imageUrl: "https://mario.wiki.gallery/images/f/f3/Panini_SMTCC_101.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "33",
      price: 270,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-07T11:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "33",
        name: "불뚝복어 (#088)",
        imageUrl: "https://mario.wiki.gallery/images/0/0a/Panini_SMTCC_088.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "32",
      price: 110,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-07T10:00:00.000Z",
      seller: {
        id: "3",
        nickname: "버섯왕국주민",
      },
      photoCard: {
        id: "32",
        name: "가시돌이 (#079)",
        imageUrl: "https://mario.wiki.gallery/images/d/d6/Panini_SMTCC_079.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "31",
      price: 120,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-07T09:00:00.000Z",
      seller: {
        id: "17",
        nickname: "교환신청중",
      },
      photoCard: {
        id: "31",
        name: "가봉 (#067)",
        imageUrl: "https://mario.wiki.gallery/images/4/48/Panini_SMTCC_067.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "30",
      price: 150,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-06T13:00:00.000Z",
      seller: {
        id: "18",
        nickname: "민트컬렉션",
      },
      photoCard: {
        id: "30",
        name: "키노피코 (#054)",
        imageUrl: "https://mario.wiki.gallery/images/9/98/Panini_SMTCC_054.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "29",
      price: 280,
      initialQuantity: 3,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-06T12:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "29",
        name: "핑크요시 (#041)",
        imageUrl: "https://mario.wiki.gallery/images/5/55/Panini_SMTCC_041.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "28",
      price: 200,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-06T11:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "28",
        name: "베이비루이지 (#028)",
        imageUrl: "https://mario.wiki.gallery/images/9/92/Panini_SMTCC_028.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "27",
      price: 200,
      initialQuantity: 3,
      remainingQuantity: 3,
      status: "ON_SALE",
      createdAt: "2026-08-06T10:00:00.000Z",
      seller: {
        id: "14",
        nickname: "카드보관소",
      },
      photoCard: {
        id: "27",
        name: "쿠파주니어 (#016)",
        imageUrl: "https://mario.wiki.gallery/images/3/37/Panini_SMTCC_016.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "26",
      price: 200,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-06T09:00:00.000Z",
      seller: {
        id: "11",
        nickname: "전설의교환가",
      },
      photoCard: {
        id: "26",
        name: "피치공주 (#003)",
        imageUrl: "https://mario.wiki.gallery/images/b/b2/Panini_SMTCC_003.jpg",
        grade: "COMMON",
        category: "SUPER_MARIO",
      },
    },
    {
      id: "25",
      price: 110,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-05T13:00:00.000Z",
      seller: {
        id: "3",
        nickname: "버섯왕국주민",
      },
      photoCard: {
        id: "25",
        name: "코로코로쿠리링",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-kuririn-1.png",
        grade: "SUPER_RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "24",
      price: 210,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-05T12:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "24",
        name: "우사하나",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-usahana.png",
        grade: "RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "23",
      price: 200,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-05T11:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "23",
        name: "키리미짱.",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-kirimichan.png",
        grade: "SUPER_RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "22",
      price: 180,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-05T10:00:00.000Z",
      seller: {
        id: "12",
        nickname: "키티프렌즈",
      },
      photoCard: {
        id: "22",
        name: "어그레츠코",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-retsuko.png",
        grade: "LEGENDARY",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "21",
      price: 240,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-05T09:00:00.000Z",
      seller: {
        id: "3",
        nickname: "버섯왕국주민",
      },
      photoCard: {
        id: "21",
        name: "초코캣",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-chococat.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "20",
      price: 80,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-04T13:00:00.000Z",
      seller: {
        id: "10",
        nickname: "마리오점퍼",
      },
      photoCard: {
        id: "20",
        name: "딩구리데이즈",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-marumofubiyori.png",
        grade: "RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "19",
      price: 190,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-04T12:00:00.000Z",
      seller: {
        id: "5",
        nickname: "디지털테이머",
      },
      photoCard: {
        id: "19",
        name: "마이스윗피아노",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-mysweetpiano.png",
        grade: "LEGENDARY",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "18",
      price: 180,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-04T11:00:00.000Z",
      seller: {
        id: "1",
        nickname: "카드수집가",
      },
      photoCard: {
        id: "18",
        name: "챠미키티",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-charmmy.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "17",
      price: 250,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-04T10:00:00.000Z",
      seller: {
        id: "10",
        nickname: "마리오점퍼",
      },
      photoCard: {
        id: "17",
        name: "배드바츠마루",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-badtzmaru-1.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "16",
      price: 280,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-04T09:00:00.000Z",
      seller: {
        id: "3",
        nickname: "버섯왕국주민",
      },
      photoCard: {
        id: "16",
        name: "위시미멜",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-wishmemell.png",
        grade: "SUPER_RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "15",
      price: 210,
      initialQuantity: 2,
      remainingQuantity: 2,
      status: "ON_SALE",
      createdAt: "2026-08-03T13:00:00.000Z",
      seller: {
        id: "9",
        nickname: "구름위시나몬",
      },
      photoCard: {
        id: "15",
        name: "아히루노페클",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-pekkle.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "14",
      price: 90,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-03T12:00:00.000Z",
      seller: {
        id: "3",
        nickname: "버섯왕국주민",
      },
      photoCard: {
        id: "14",
        name: "리틀트윈스타",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-kikilala.png",
        grade: "RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "13",
      price: 80,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-03T11:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "13",
        name: "폼폼푸린",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-pompompurin.png",
        grade: "RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "12",
      price: 170,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-03T10:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "12",
        name: "하나마루오바케",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2023/03/mv-hanamaruobake.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "11",
      price: 290,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-03T09:00:00.000Z",
      seller: {
        id: "10",
        nickname: "마리오점퍼",
      },
      photoCard: {
        id: "11",
        name: "케로케로케로피",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-keroppi.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "10",
      price: 210,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-02T13:00:00.000Z",
      seller: {
        id: "14",
        nickname: "카드보관소",
      },
      photoCard: {
        id: "10",
        name: "헬로키티",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-hellokitty.png",
        grade: "LEGENDARY",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "9",
      price: 80,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-02T12:00:00.000Z",
      seller: {
        id: "13",
        nickname: "몬스터도감",
      },
      photoCard: {
        id: "9",
        name: "코기뮹",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-cogimyun-1.png",
        grade: "LEGENDARY",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "8",
      price: 170,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-02T11:00:00.000Z",
      seller: {
        id: "20",
        nickname: "앨범완성가",
      },
      photoCard: {
        id: "8",
        name: "턱시도샘",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-tuxedosam.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "7",
      price: 120,
      initialQuantity: 2,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-02T10:00:00.000Z",
      seller: {
        id: "15",
        nickname: "슈퍼레어픽",
      },
      photoCard: {
        id: "7",
        name: "쿠로미",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-kuromi.png",
        grade: "SUPER_RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "6",
      price: 270,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-02T09:00:00.000Z",
      seller: {
        id: "7",
        nickname: "레어헌터",
      },
      photoCard: {
        id: "6",
        name: "마론크림",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-marroncream-1.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "5",
      price: 260,
      initialQuantity: 1,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-01T13:00:00.000Z",
      seller: {
        id: "20",
        nickname: "앨범완성가",
      },
      photoCard: {
        id: "5",
        name: "포차코",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-pochacco.png",
        grade: "SUPER_RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "4",
      price: 100,
      initialQuantity: 2,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-01T12:00:00.000Z",
      seller: {
        id: "4",
        nickname: "리본컬렉터",
      },
      photoCard: {
        id: "4",
        name: "구데타마",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-gudetama.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "3",
      price: 120,
      initialQuantity: 3,
      remainingQuantity: 1,
      status: "ON_SALE",
      createdAt: "2026-08-01T11:00:00.000Z",
      seller: {
        id: "14",
        nickname: "카드보관소",
      },
      photoCard: {
        id: "3",
        name: "마이멜로디",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/list-mymelody.png",
        grade: "RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "2",
      price: 220,
      initialQuantity: 1,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-01T10:00:00.000Z",
      seller: {
        id: "11",
        nickname: "전설의교환가",
      },
      photoCard: {
        id: "2",
        name: "한교동",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-hangyodon-1.png",
        grade: "SUPER_RARE",
        category: "HELLO_KITTY",
      },
    },
    {
      id: "1",
      price: 80,
      initialQuantity: 3,
      remainingQuantity: 0,
      status: "SOLD_OUT",
      createdAt: "2026-08-01T09:00:00.000Z",
      seller: {
        id: "2",
        nickname: "피카츄러버",
      },
      photoCard: {
        id: "1",
        name: "시나모롤",
        imageUrl: "https://www.sanrio.co.jp/wp-content/uploads/2022/06/mv-cinnamon.png",
        grade: "COMMON",
        category: "HELLO_KITTY",
      },
    },
  ],
  nextCursor: null,
  hasNext: false,
};
